import cors, { CorsOptions } from "cors";
import express, { Application, Express } from "express";
import config from "./config";
import compression from "compression";
import helmet from "helmet";
import { ServerEnvOptions } from "./utils/enums/config.enums";
import morgan from "morgan";
import fs from "fs";
import customMiddleware from "./middlewares/custom.middleware";
import routes from "./routes";
import errorMiddleware from "./middlewares/error.middleware";
import db from "./db";
import http from "http";
import NotificationService from "./services/notificationService";
